//*****************************************************************************
// TextureManager.h
// Author : Mane
//*****************************************************************************
#ifndef TEXTUREMANAGER_H
#define TEXTUREMANAGER_H

#include "Texture.h"

//*****************************************************************************
// エナム
//*****************************************************************************
enum TEXTURES_ID
{
	//ロゴのテクスチャ
	TEXTURE_LOGO=0,
	//タイトルスクリーンのテクスチャ
	TEXTURE_TITLE,
	//メニューに関するテクスチャ
	TEXTURE_SCROLLING_BACKGROUND,
	TEXTURE_RANKING_SCROLLING_BACKGROUND,
	TEXTURE_EXTRA_SCROLLING_BACKGROUND,
	TEXTURE_MENU_DECORATION_OBJECT,
	TEXTURE_MENU_DEBUG_ROOM,
	TEXTURE_MENU_STARTGAME,
	TEXTURE_MENU_TUTORIAL_ROOM,
	TEXTURE_MENU_RANKINGS,
	TEXTURE_MENU_EXTRA_OPTIONS,
	TEXTURE_MENU_EXIT,
	TEXTURE_MENU_NSNG_ACTIVATED,
	TEXTURE_MENU_NSNG_DEACTIVATED,
	TEXTURE_MENU_FPS_ACTIVATE,
	TEXTURE_MENU_FPS_DEACTIVATE,
	TEXTURE_MENU_HELLSTOUCH_ACTIVATED,
	TEXTURE_MENU_HELLSTOUCH_DEACTIVATED,
	TEXTURE_MENU_RETURN,
	TEXTURE_MENU_NSNG_INFO,
	TEXTURE_MENU_HM_INFO,
	//UIに関する
	TEXTURE_PAUSE_CONTROLS,
	TEXTURE_PAUSE_MOVES,
	TEXTURE_UI_HEARTS,
	TEXTURE_UI_RANK,
	TEXTURE_UI_MINIAURA,
	TEXTURE_UI_NUMBERS,
	TEXTURE_UI_RANKNUMBERS,
	TEXTURE_UI_EVENTMESSAGE_START,
	TEXTURE_UI_EVENTMESSAGE_OVER,
	TEXTURE_UI_EVENTMESSAGE_ONAIR,
	TEXTURE_UI_RANKINGTEXT_COMBO,
	TEXTURE_UI_RANKINGTEXT_TIME,
	TEXTURE_UI_RANKINGTEXT_DAMAGE,
	TEXTURE_UI_RANKINGTEXT_OVERRAL,
	TEXTURE_UI_RANKINGTEXT_RESULTSTEXT,
	TEXTURE_UI_RANKINGTEXT_RANK,
	TEXTURE_UI_PAUSETEXT,
	TEXTURE_UI_STAGECLEAR_BACKGROUND,
	TEXTURE_UI_GENERAL_RANKING,
	TEXTURE_UI_TUTORIAL_TEXT,
	TEXTURE_UI_RANKING_DEBUGROOM_TEXT,
	TEXTURE_UI_RANKING_TUTORIALROOM_TEXT,
	TEXTURE_UI_RANKING_LEVEL1ROOM_TEXT,
	TEXTURE_UI_PAUSE_OPTIONS_CONTINUE,
	TEXTURE_UI_PAUSE_OPTIONS_CONTROLS,
	TEXTURE_UI_PAUSE_OPTIONS_COMMANDS,
	TEXTURE_UI_PAUSE_OPTIONS_RETURNTITLE,
	TEXTURE_UI_ARROW,
	TEXTURE_UI_ATK_EFFECT,
	TEXTURE_UI_ATK_EFFECT_ALT,
	TEXTURE_UI_EDITOR_INSTRUCTIONS_1,
	TEXTURE_UI_EDITOR_INSTRUCTIONS_2,
	TEXTURE_UI_EDITOR_SLOT_TEXT,
	TEXTURE_UI_EDITOR_SPEED_TEXT,
	TEXTURE_UI_EDITOR_DELAY_TEXT,
	TEXTURE_UI_CONTROLLER_TUTORIAL_MOVE,
	TEXTURE_UI_CONTROLLER_TUTORIAL_JUMP,
	TEXTURE_UI_CONTROLLER_TUTORIAL_ATTACK,
	TEXTURE_UI_CONTROLLER_TUTORIAL_GUITAR_DASH,
	TEXTURE_UI_CONTROLLER_TUTORIAL_GUITAR_SHOOT,
	TEXTURE_UI_CONTROLLER_TUTORIAL_CATCH_BULLET,
	TEXTURE_UI_LEVEL_SAVED_TEXT,
	TEXTURE_UI_LEVEL_LOADED_TEXT,
	MAX_TEXTURES_UI,
	//ゲームオーバーに関するテクスチャ
	TEXTURE_REDNOISE,
	TEXTURE_GAMEOVER_MESSAGE,
	//床に関しているテクスチャ
	DOMINOS_FLOOR_BLACK_TEXTURE,
	REGULAR_FLOOR_PURPLE_TEXTURE,
	REGULAR_FLOOR_YELLOW_TEXTURE,
	REGULAR_FLOOR_RED_TEXTURE,
	DOMINOS_FLOOR_YELLOW_TEXTURE,
	MAX_TEXTURE_FLOORS,
	//プレイヤーの花
	TEXTURE_FLOWERS,
	TEXTURE_FLOWERS_SPEED,
	//壁のテクスチャー
	EVIL_BLOCK_TEXTURE,
	EVIL_BLOCK2_TEXTURE,
	EVIL_BLOCK3_TEXTURE,
	MAX_TEXTURES_WALLS,
	//ゲームオブジェクトに関するテクスチャ
	TEXTURE_SPIKE,
	TEXTURE_TELEPORTER,
	TEXTURE_PUNCHABLE_STAR,
	TEXTURE_SWITCH_SHOOT,
	TEXTURE_SWITCH_PUNCH,
	TEXTURE_SOBA,
	TEXTURE_CRYSTAL,
	TEXTURE_ENDPOINT_TELEPORTER,
	MAX_TEXTURES_LEVELOBJECTS,
	//プレイヤーに関するテクスチャ
	TEXTURE_SPOTLIGHT,
	TEXTURE_DEBUG_AIM,
	TEXTURE_DEBUG_X_GREEN,
	TEXTURE_DEBUG_X_BLUE,
	TEXTURE_COMMON_BULLETS,
	TEXTURE_CATCH_BULLETS,
	TEXTURE_BLACKSPOT,
	TEXTURE_PLAYER,
	TEXTURE_HALO,
	TEXTURE_AURA_EFFECT_PLAYER,
	TEXTURE_WEAPON_HANDS,
	TEXTURE_WEAPON_GUITAR,
	MAX_TEXTURES_WEAPONS,
	//敵のテクスチャ
	TEXTURE_BUNBUN_ENEMY,
	MAX_TEXTURE_ENEMIES,
	TEXTURE_BUNBUN_ENEMYLOGO,
	//MISC
	TEXTURE_BACKGROUND1,
	TEXTURE_BACKGROUND2,
	TEXTURE_BACKGROUND3,
	TEXTURE_BACKGROUNDEVENT,
	TEXTURE_HITBOX,
	MAX_TEXTURES
};

//*****************************************************************************
// プロトタイプ宣言
//*****************************************************************************
void InitTextures();
ID3D11ShaderResourceView* GetTexture(int TextureID);
void EndTextures();
void EndFloorTextures();
void EndWallTextures();
void EndLevelObjectsTextures();
void EndEnemyTextures();
int GetTextureCountInMemory();

#endif